# Generated by Django 5.0.1 on 2024-01-12 18:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_doors_alter_car_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='descriptions',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
